# Site settings
title: LBJ's world
email: lbj.world@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Technology, Product, Speed
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lbjworld.github.io" # the base hostname & protocol for your site
twitter_username: BJ_Lan
github_username:  lbjworld

# Build settings
markdown: kramdown
