# Site settings
title: LBJ's little world
email: lbj.world@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technology, Product, Speed
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://lbjworld.github.io" # the base hostname & protocol for your site
twitter_username: lbjworld
github_username:  lbjworld

# Build settings
markdown: kramdown
